# frozen_string_literal: true

source 'https://rubygems.org'

gem 'aws-sdk-s3', '~> 1'
gem 'activerecord-in_batches', git: 'https://github.com/siadat/in_batches.git'
gem 'blacklight', '>= 6.0.0'
gem 'blacklight-gallery'
gem 'blacklight-maps'
gem 'blacklight_advanced_search'
gem 'bootstrap_form'
gem 'bundler', '< 2.0'
gem 'cancancan', '~> 1.15'
gem 'carrierwave', '~> 1.3'
gem 'chosen-rails'
gem 'coffee-rails', '~> 4.1.0'
gem 'devise'
gem 'devise_invitable'
gem 'diffy'
gem 'exception_notification'
gem 'geocoder'
gem 'gretel'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'jquery-turbolinks'
gem 'json', '>= 2.3.0'
gem 'multi-select-rails'
gem 'paper_trail'
gem 'pg'
gem 'rails', '~> 4'
gem 'redis'
gem 'resque'
gem 'rsolr'
gem 'rubyzip'
gem 'sass-rails', '~> 5.0'
# gem 'sdoc', '~> 0.4.0', group: :doc
gem 'slack-notifier'
gem 'sunspot_rails'
gem 'turbolinks'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
gem 'uglifier', '>= 1.3.0'

group :test do
  gem 'capybara'
  gem 'capybara-screenshot'
  gem 'fabrication'
  gem 'faker'
  gem 'poltergeist'
  gem 'resque_spec'
  gem 'rspec-mocks'
  gem 'rspec-rails', '~> 3.0'
  gem 'simplecov'
  gem 'transactional_capybara'
end

group :development do
  gem 'quiet_assets'
  gem 'spring'
  gem 'web-console', '~> 2.0'
  gem 'xray-rails'
end