Fabricator(:holding_institution) do
  display_name        "MyString"
  short_description   "MyText"
  description         "MyText"
  image               "MyString"
  homepage_url        "MyString"
  coordinates         "MyString"
  strengths           "MyText"
  contact_information "MyText"
  type                ""
  galileo_member      false
  contact_name        "MyString"
  contact_email       "MyString"
  harvest_strategy    "MyString"
  oai_url             "MyString"
  ignored_collections "MyText"
  last_harvested_at   "2018-08-15 15:58:02"
  analytics_emails    "MyText"
  subgranting         "MyText"
  grant_partnerships  "MyText"
end
